# Generated by Django 6.0.2 on 2026-02-10 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('theatres', '0002_delete_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('LOCKED', 'Locked'), ('BOOKED', 'Booked')], max_length=10)),
                ('locked_at', models.DateTimeField(auto_now_add=True)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theatres.seat')),
            ],
        ),
    ]
