# Generated by Django 6.0.2 on 2026-02-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_seatbooking_locked_at_alter_seatbooking_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatbooking',
            name='locked_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
