# Generated by Django 6.0.2 on 2026-02-10 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theatres', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Show',
        ),
    ]
