# Generated by Django 6.0.2 on 2026-02-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='movies/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('ENG', 'English'), ('HIN', 'Hindi'), ('TEL', 'Telugu'), ('TAM', 'Tamil'), ('MAL', 'Malayalam')], max_length=10),
        ),
    ]
