# Generated by Django 6.0.2 on 2026-02-18 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_banner_alter_movie_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoviePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='cast/')),
                ('type', models.CharField(choices=[('CAST', 'Cast'), ('CREW', 'Crew')], max_length=10)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='movies.movie')),
            ],
        ),
    ]
